contact_links:
  - name: Q&A Support
    url: https://fortran-lang.discourse.group/c/help/vscode/
    about: Have a Question about the extension or need support? Ask a question in the Fortran Discourse.
  - name: Modern Fortran discussion board
    url: https://github.com/fortran-lang/vscode-fortran-support/discussions
    about: Have an Idea about the extension or a General inquiry that is not about Support? Start a discussion on the Modern Fortran Discussion Board.
  - name: fortls Language Server discusion board
    url: https://github.com/gnikit/fortls/discussions
    about: Problems with the Language Server? Start a discussion on the fortls Language Server Discussion Board.
  - name: Fortran-lang discourse
    url: https://fortran-lang.discourse.group/
    about: Discussion about all things Fortran
  - name: Fortran-lang mailing list
    url: https://groups.io/g/fortran-lang
    about: Mailinglist for the Fortran language
